require 'jekyll-theme-al-folio/cache-bust'
require 'jekyll-theme-al-folio/details'
require 'jekyll-theme-al-folio/download-3rd-party'
require 'jekyll-theme-al-folio/external-posts'
require 'jekyll-theme-al-folio/file-exists'
require 'jekyll-theme-al-folio/google-scholar-citations'
require 'jekyll-theme-al-folio/hide-custom-bibtex'
require 'jekyll-theme-al-folio/remove-accents'
